# Generated by Django 4.2.23 on 2025-08-21 02:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RealEstate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('location', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=16, unique=True)),
                ('email', models.EmailField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='House',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('house_type', models.CharField(max_length=10)),
                ('price', models.IntegerField()),
                ('building_area', models.IntegerField()),
                ('land_area', models.IntegerField()),
                ('facility', models.TextField()),
                ('spesification', models.TextField()),
                ('real_estate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sirumah.realestate')),
            ],
        ),
    ]
