# Generated by Django 4.2.23 on 2025-08-21 03:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sirumah', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='realestate',
            name='location',
        ),
    ]
