# Generated by Django 4.2.23 on 2025-08-21 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sirumah', '0002_remove_realestate_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='realestate',
            name='district',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='realestate',
            name='province',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='realestate',
            name='subdistrict',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='realestate',
            name='village',
            field=models.CharField(default='', max_length=50),
        ),
    ]
