# Generated by Django 4.2.23 on 2025-08-21 03:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sirumah', '0003_realestate_district_realestate_province_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('phone_number', models.CharField(max_length=16, unique=True)),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('province', models.CharField(max_length=20)),
                ('district', models.CharField(max_length=100)),
                ('subdistrict', models.CharField(max_length=50)),
                ('village', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=150)),
            ],
        ),
        migrations.RemoveField(
            model_name='realestate',
            name='email',
        ),
        migrations.RemoveField(
            model_name='realestate',
            name='phone_number',
        ),
        migrations.AddField(
            model_name='realestate',
            name='company',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='sirumah.company'),
        ),
    ]
