# Generated by Django 4.2.23 on 2025-08-21 03:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sirumah', '0004_company_remove_realestate_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='realestate',
            name='company',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='sirumah.company'),
        ),
    ]
