# Generated by Django 4.2.23 on 2025-08-25 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sirumah', '0005_alter_realestate_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='house',
            name='building_area',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='house',
            name='land_area',
            field=models.FloatField(),
        ),
    ]
