# Generated by Django 4.2.23 on 2025-08-26 15:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sirumah', '0006_alter_house_building_area_alter_house_land_area'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='house',
            name='facility',
        ),
        migrations.RemoveField(
            model_name='house',
            name='spesification',
        ),
        migrations.CreateModel(
            name='HouseAttribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attribute_type', models.CharField(choices=[('facility', 'Facility'), ('spec', 'Specification')], max_length=10)),
                ('name', models.CharField(max_length=100)),
                ('value', models.CharField(max_length=255)),
                ('house', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attributes', to='sirumah.house')),
            ],
        ),
    ]
