# Generated by Django 5.2.5 on 2025-09-01 10:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sirumah', '0007_remove_house_facility_remove_house_spesification_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HouseWeights',
            fields=[
                ('house', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='sirumah.house')),
                ('location', models.IntegerField()),
                ('price', models.IntegerField()),
                ('building_area', models.IntegerField()),
                ('land_area', models.IntegerField()),
                ('specification', models.IntegerField()),
                ('facility', models.IntegerField()),
            ],
        ),
    ]
