# Generated by Django 5.2.5 on 2025-09-24 00:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sirumah', '0008_houseweights'),
    ]

    operations = [
        migrations.CreateModel(
            name='CriteriaWegiths',
            fields=[
                ('criteria_name', models.CharField(max_length=100, primary_key=True, serialize=False, unique=True)),
                ('criteria_label', models.CharField(max_length=100)),
                ('criteria_weight', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='SubCriteriaWeights',
            fields=[
                ('sub_criteria_name', models.CharField(max_length=100, primary_key=True, serialize=False, unique=True)),
                ('sub_criteria_label', models.CharField(max_length=100)),
                ('sub_criteria_weight', models.IntegerField()),
                ('criteria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sirumah.criteriawegiths')),
            ],
        ),
    ]
