# Generated by Django 5.2.5 on 2025-09-26 06:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sirumah', '0009_criteriawegiths_subcriteriaweights'),
    ]

    operations = [
        migrations.CreateModel(
            name='Criteria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='subcriteriaweights',
            name='criteria',
        ),
        migrations.CreateModel(
            name='CriteriaWeight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.IntegerField()),
                ('criteria', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='sirumah.criteria')),
            ],
        ),
        migrations.CreateModel(
            name='SubCriteria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('criteria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sirumah.criteria')),
            ],
        ),
        migrations.CreateModel(
            name='SubCriteriaWeight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.IntegerField()),
                ('sub_criteria', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='sirumah.subcriteria')),
            ],
        ),
        migrations.DeleteModel(
            name='CriteriaWegiths',
        ),
        migrations.DeleteModel(
            name='SubCriteriaWeights',
        ),
    ]
