# Generated by Django 5.2.5 on 2025-10-02 10:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sirumah', '0010_criteria_remove_subcriteriaweights_criteria_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CriteriaWeight',
        ),
    ]
