from django import forms


class FindHouseWeightForm(forms.Form):
    location = forms.IntegerField(label='Lokasi', required=True, min_value=1, max_value=9)
    price = forms.IntegerField(label='Harga', required=True, min_value=1, max_value=9)
    building_area = forms.IntegerField(label='Luas Bangunan', required=True, min_value=1, max_value=9)
    land_area = forms.IntegerField(label='Luas Tanah', required=True, min_value=1, max_value=9)
    specification = forms.IntegerField(label='Spesifikasi', required=True, min_value=1, max_value=9)
    facility = forms.IntegerField(label='Fasilitas', required=True, min_value=1, max_value=9)
    sub_location_c1 = forms.IntegerField(label='Sub Lokasi C1', required=False, min_value=1, max_value=9)
    sub_location_c2 = forms.IntegerField(label='Sub Lokasi C2', required=False, min_value=1, max_value=9)
    sub_location_c3 = forms.IntegerField(label='Sub Lokasi C3', required=False, min_value=1, max_value=9)
    sub_price_c1 = forms.IntegerField(label='Sub Harga C1', required=False, min_value=1, max_value=9)
    sub_price_c2 = forms.IntegerField(label='Sub Harga C2', required=False, min_value=1, max_value=9)
    sub_price_c3 = forms.IntegerField(label='Sub Harga C3', required=False, min_value=1, max_value=9)
    sub_building_area_c1 = forms.IntegerField(label='Sub Luas Bangunan C1', required=False, min_value=1, max_value=9)
    sub_building_area_c2 = forms.IntegerField(label='Sub Luas Bangunan C2', required=False, min_value=1, max_value=9)
    sub_building_area_c3 = forms.IntegerField(label='Sub Luas Bangunan C3', required=False, min_value=1, max_value=9)
    sub_land_area_c1 = forms.IntegerField(label='Sub Luas Tanah C1', required=False, min_value=1, max_value=9)
    sub_land_area_c2 = forms.IntegerField(label='Sub Luas Tanah C2', required=False, min_value=1, max_value=9)
    sub_land_area_c3 = forms.IntegerField(label='Sub Luas Tanah C3', required=False, min_value=1, max_value=9)
    sub_specification_c1 = forms.IntegerField(label='Sub Spesifikasi C1', required=False, min_value=1, max_value=9)
    sub_specification_c2 = forms.IntegerField(label='Sub Spesifikasi C2', required=False, min_value=1, max_value=9)
    sub_specification_c3 = forms.IntegerField(label='Sub Spesifikasi C3', required=False, min_value=1, max_value=9)
    sub_facility_c1 = forms.IntegerField(label='Sub Fasilitas C1', required=False, min_value=1, max_value=9)
    sub_facility_c2 = forms.IntegerField(label='Sub Fasilitas C2', required=False, min_value=1, max_value=9)
    sub_facility_c3 = forms.IntegerField(label='Sub Fasilitas C3', required=False, min_value=1, max_value=9)